esphome:
  name: doorsensor
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret iot_wifi_ssid
  password: !secret iot_wifi_password
  fast_connect: on
  manual_ip:
    static_ip: '192.168.9.30'
    gateway: '192.168.9.2'
    subnet: '255.255.255.0'

# Enable logging
logger:

# Do Not Enable Home Assistant API
#api:

ota:

web_server:
  port: 80

mqtt:
  broker: '192.168.9.43'
  username: 'door'
  password: !secret iot_mqtt_door_passsword

binary_sensor:
  - platform: gpio
    pin:
      number: D2
      mode: INPUT_PULLUP
    name: "door"
    device_class: door
  - platform: gpio
    pin:
      number: D3
      mode: INPUT_PULLUP
      inverted: True
    name: "doorbell"
    device_class: sound
    filters:
      - delayed_on: 10ms
  - platform: gpio
    pin:
      number: D1
      mode: INPUT_PULLUP
      inverted: True
    name: "doorswipe"
    device_class: motion
    filters:
      - delayed_on: 5ms
